import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
export default function Home(props) {
  // console.log(value);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Value SSR: {props.value}</p>
    </div>
  );
}

// export async function getSaticProps() {
//  const res = await axios.get("https://api.chucknorris.io/jokes/random");
//   console.log(res.data.value);
//   return {
//     props: {
//       value: res.data.value,
//     },
//   };
// }
export const getStaticProps = async () => {
  const res = await axios.get("https://api.chucknorris.io/jokes/random");
  console.log(res.data.value);
  return {
    props: {
      value: res.data.value,
    },
  };
};
