import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState, useEffect } from "react";
import Search from "@/layout/Search/Search";
import { searchRepos } from "services/githubService";

export default function Home() {
  // console.log(value);
  const [searchText, setSearchText] = useState("");
  const [language, setLanguage] = useState("");
  const [repos, setRepos] = useState([]);
  const [loading, setLoading] = useState(false);
  // const apiKey = process.env.REACT_APP_API_KEY;
  // console.log(process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID);
  const onSearchTextChange = (text) => {
    setSearchText(text);
    loadRepos(text, language);
  };

  const onLanguageChange = (language) => {
    setLanguage(language);
    loadRepos(searchText, language);
  };

  const loadRepos = async (searchText, language) => {
    setLoading(true);
    const res = await searchRepos(searchText, language);
    setLoading(false);
    setRepos(res.data.items);
  };
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <p>Value SSR: {props.value}</p>
    // </div>
    <div>
      <Search
        searchText={searchText}
        language={language}
        onSearchTextChange={onSearchTextChange}
        onLanguageChange={onLanguageChange}
      />
      {loading ? "Loading..." : <div>{JSON.stringify(repos, null, 2)}</div>}
    </div>
  );
}

// export async function getSaticProps() {
//  const res = await axios.get("https://api.chucknorris.io/jokes/random");
//   console.log(res.data.value);
//   return {
//     props: {
//       value: res.data.value,
//     },
//   };
// }
export const getStaticProps = async () => {
  const res = await axios.get("https://api.chucknorris.io/jokes/random");
  console.log(res.data.value);
  return {
    props: {
      value: res.data.value,
    },
  };
};
